// @ts-nocheck
/* eslint-disable */
// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	getSettings: () => typedError<Settings, AppError>(__TAURI_INVOKE("get_settings")),
	setLaunchAtStartup: (enabled: boolean) => typedError<Settings, AppError>(__TAURI_INVOKE("set_launch_at_startup", { enabled })),
	getAppVersion: () => __TAURI_INVOKE<string>("get_app_version"),
	openLogsFolder: () => typedError<null, AppError>(__TAURI_INVOKE("open_logs_folder")),
	/**
	 *  Erreur de l'interface (gestionnaire global Vue, rejet de promesse) à écrire au
	 *  journal du client. Jamais d'erreur en retour : l'interface ne doit pas
	 *  échouer en rapportant un échec. Message borné en taille, débit limité.
	 */
	logFrontendError: (source: string, message: string) => __TAURI_INVOKE<void>("log_frontend_error", { source, message }),
	/**  Réglage « Notifier quand un serveur devient hors ligne ou revient » (BR-RESIL-015) : activé par défaut. */
	getNotifyOnLinkChange: () => typedError<boolean, AppError>(__TAURI_INVOKE("get_notify_on_link_change")),
	setNotifyOnLinkChange: (enabled: boolean) => typedError<boolean, AppError>(__TAURI_INVOKE("set_notify_on_link_change", { enabled })),
	/**
	 *  Le serveur affiché dans la fenêtre (`None` : aucun, réglages par exemple) : l'icône de la zone de
	 *  notification reflète son état (BR-RESIL-016).
	 */
	setDisplayedServer: (serverId: string | null) => __TAURI_INVOKE<void>("set_displayed_server", { serverId }),
	listServers: () => __TAURI_INVOKE<ServerDto[]>("list_servers"),
	listLinkStates: () => __TAURI_INVOKE<LinkStateDto[]>("list_link_states"),
	probeServer: (host: string, port: number | null) => typedError<ProbeDto, LinkFailure>(__TAURI_INVOKE("probe_server", { host, port })),
	/**  Fin de l'assistant d'ajout : le serveur n'est enregistré que si la connexion réussit. */
	addAndLogin: (input: AddServerInput) => typedError<ServerDto, LinkFailure>(__TAURI_INVOKE("add_and_login", { input })),
	login: (serverId: string, username: string, password: string, remember: boolean) => typedError<LoginDto, LinkFailure>(__TAURI_INVOKE("login", { serverId, username, password, remember })),
	logout: (serverId: string) => typedError<null, LinkFailure>(__TAURI_INVOKE("logout", { serverId })),
	retryNow: (serverId: string) => typedError<null, LinkFailure>(__TAURI_INVOKE("retry_now", { serverId })),
	acceptFingerprint: (serverId: string, fingerprint: string) => typedError<null, LinkFailure>(__TAURI_INVOKE("accept_fingerprint", { serverId, fingerprint })),
	updateServer: (serverId: string, name: string, color: number, host: string, port: number | null, fingerprint: string | null) => typedError<ServerDto, LinkFailure>(__TAURI_INVOKE("update_server", { serverId, name, color, host, port, fingerprint })),
	removeServer: (serverId: string) => typedError<null, LinkFailure>(__TAURI_INVOKE("remove_server", { serverId })),
	forgetCredentials: (serverId: string) => typedError<null, LinkFailure>(__TAURI_INVOKE("forget_credentials", { serverId })),
	/**  Alertes d'empreinte en attente de décision : à lire après l'abonnement à `link://fingerprint`. */
	listFingerprintAlerts: () => __TAURI_INVOKE<FingerprintEvent[]>("list_fingerprint_alerts"),
	/**  Avis de la liaison retenus tant qu'ils ne sont pas acquittés (lecture non destructive). */
	listLinkNotices: () => __TAURI_INVOKE<NoticeEvent[]>("list_link_notices"),
	ackLinkNotices: (ids: number[]) => __TAURI_INVOKE<void>("ack_link_notices", { ids }),
	/**  Issues d'actions retenues tant qu'elles ne sont pas acquittées (lecture non destructive). */
	listUnreadOperations: () => __TAURI_INVOKE<OperationEventDto[]>("list_unread_operations"),
	ackUnreadOperations: (opIds: string[]) => __TAURI_INVOKE<void>("ack_unread_operations", { opIds }),
	/**
	 *  Dernière vue connue de la machine d'un serveur (tableau de bord) : à lire après l'abonnement à
	 *  `link://snapshot` et `link://metrics`. `None` tant qu'aucune identité n'a été reçue.
	 */
	getDashboard: (serverId: string) => typedError<{
	serverId: string,
	machine: MachineDto,
	history: SampleDto[],
	levels: LevelsDto | null,
} | null, LinkFailure>(__TAURI_INVOKE("get_dashboard", { serverId })),
	/**  L'état courant (au démarrage de l'interface, et pour rattraper un événement manqué). */
	getUpdateState: () => __TAURI_INVOKE<UpdateStateDto>("get_update_state"),
	/**  « Vérifier maintenant » (BR-UPDATE-026). */
	checkForUpdates: () => __TAURI_INVOKE<UpdateStateDto>("check_for_updates"),
	/**  « Plus tard » : le bandeau disparaît 24 h (BR-UPDATE-006). */
	postponeUpdate: () => __TAURI_INVOKE<UpdateStateDto>("postpone_update"),
	/**
	 *  « Mettre à jour maintenant » : le seul chemin vers une installation (BR-UPDATE-002). Rend la
	 *  main tout de suite ; l'avancement et l'issue arrivent par `update://state`.
	 */
	installUpdate: () => __TAURI_INVOKE<UpdateStateDto>("install_update"),
	/**
	 *  Saisie en direct d'un identifiant et d'un mot de passe : règles de `hearth-proto`, aucun
	 *  réseau. L'agent reste l'arbitre à l'envoi.
	 */
	checkAccountInput: (username: string, password: string) => __TAURI_INVOKE<AccountInputCheck>("check_account_input", { username, password }),
	/**
	 *  La liste des comptes (administrateurs ; l'agent refuse les autres) et l'identifiant de l'agent
	 *  du compte de la session.
	 */
	listAccounts: (serverId: string) => typedError<AccountListDto, LinkFailure>(__TAURI_INVOKE("list_accounts", { serverId })),
	createAccount: (serverId: string, username: string, password: string, role: RoleDto) => typedError<AccountOutcome, LinkFailure>(__TAURI_INVOKE("create_account", { serverId, username, password, role })),
	changeAccountRole: (serverId: string, accountId: string, role: RoleDto) => typedError<AccountOutcome, LinkFailure>(__TAURI_INVOKE("change_account_role", { serverId, accountId, role })),
	/**
	 *  Un administrateur définit le mot de passe d'un autre compte (ferme ses sessions). La règle « ne
	 *  contient pas l'identifiant » est celle de l'agent, qui lit le compte lui-même.
	 */
	setAccountPassword: (serverId: string, accountId: string, password: string) => typedError<AccountOutcome, LinkFailure>(__TAURI_INVOKE("set_account_password", { serverId, accountId, password })),
	/**
	 *  Le titulaire change son propre mot de passe (ferme ses AUTRES sessions, garde la courante) ;
	 *  le mot de passe mémorisé au coffre suit (voir `service::change_own_password`).
	 */
	changeOwnPassword: (serverId: string, current: string, password: string) => typedError<AccountOutcome, LinkFailure>(__TAURI_INVOKE("change_own_password", { serverId, current, password })),
	closeAccountSessions: (serverId: string, accountId: string) => typedError<AccountOutcome, LinkFailure>(__TAURI_INVOKE("close_account_sessions", { serverId, accountId })),
	/**  Supprime un compte. `confirmation` : l'identifiant retapé quand on supprime son propre compte. */
	deleteAccount: (serverId: string, accountId: string, confirmation: string | null) => typedError<AccountOutcome, LinkFailure>(__TAURI_INVOKE("delete_account", { serverId, accountId, confirmation })),
};

/* Types */
/**
 *  Un compte de la liste d'administration. Les dates sont celles de l'agent (RFC 3339, UTC) ;
 *  l'interface les met en forme.
 */
export type AccountDto = {
	id: string,
	username: string,
	role: RoleDto,
	createdAt: string,
	lastLoginAt: string | null,
	sessionsOpen: number,
};

/**
 *  Verdict de la saisie en direct (`check_account_input`) : la règle est celle de `hearth-proto`,
 *  la même que celle de l'agent.
 */
export type AccountInputCheck = {
	username: UsernameProblemDto | null,
	password: PasswordRuleDto[],
};

/**  Résultat de la lecture de la liste. */
export type AccountListDto = 
/**
 *  `me` : l'identifiant de l'AGENT du compte de la session courante (jamais une comparaison de
 *  texte côté interface pour savoir « qui est moi »).
 */
{ kind: "listed"; accounts: AccountDto[]; me: string } | { kind: "refused"; refusal: AccountRefusal };

/**  Issue d'une action de compte. */
export type AccountOutcome = 
/**
 *  L'agent a exécuté l'action. `account` : le compte créé ; `sessions_closed` : sessions
 *  fermées (0 si l'action n'en ferme pas).
 */
{ kind: "done"; account: AccountDto | null; sessions_closed: number } | { kind: "refused"; refusal: AccountRefusal } | 
/**
 *  Le lien est tombé avant la réponse : on ne sait pas, l'action n'est JAMAIS rejouée.
 *  L'issue arrive par `link://operation` sous cet identifiant ; la liste se relit au retour du
 *  lien.
 */
{ kind: "unknown"; op_id: string };

/**
 *  Pourquoi l'agent (ou la validation locale, avant tout envoi) a refusé. Sans texte : l'interface
 *  choisit le message d'après `kind`.
 */
export type AccountRefusal = 
/**  Rôle insuffisant (BR-ACCT-013, 014) : l'agent est l'arbitre, même si le client est contourné. */
{ kind: "forbidden" } | 
/**  Identifiant au mauvais format : `problem` renseigné quand la validation locale l'a vu. */
{ kind: "invalid_username"; problem: UsernameProblemDto | null } | 
/**  Mot de passe refusé : toutes les règles non respectées. */
{ kind: "weak_password"; rules: PasswordRuleDto[] } | { kind: "username_taken" } | 
/**  L'ancien mot de passe est incorrect. */
{ kind: "wrong_password" } | 
/**  Il doit toujours rester au moins un administrateur (BR-ACCT-007). */
{ kind: "last_admin" } | { kind: "not_found" } | 
/**  L'identifiant retapé pour supprimer son propre compte ne correspond pas (BR-ACCT-012). */
{ kind: "confirmation_mismatch" } | 
/**  Le mot de passe a changé entre la vérification et l'écriture : réessayer. */
{ kind: "conflict" } | 
/**  L'agent est saturé : réessayer dans un instant. */
{ kind: "busy" } | 
/**  La session a expiré pendant l'action : l'état du lien le dit. */
{ kind: "session_ended" } | 
/**  La session a été fermée (changement de mot de passe, suppression, révocation). */
{ kind: "session_revoked" } | { kind: "other" };

/**
 *  Ce que l'assistant envoie à sa dernière étape : le serveur confirmé et les identifiants. Pas de
 *  `Debug` : il porte un mot de passe.
 */
export type AddServerInput = {
	name: string,
	color: number,
	host: string,
	port: number | null,
	/**  Empreinte confirmée par l'utilisateur, forme complète : celle de la dernière sonde. */
	fingerprint: string,
	macAddresses: string[],
	username: string,
	password: string,
	remember: boolean,
};

/**
 *  Erreur d'une commande. Sérialisée `{ kind, message }` côté TypeScript ;
 *  l'interface choisit son texte d'après `kind`.
 */
export type AppError = 
/**  Lecture ou écriture des réglages locaux impossible. */
{ kind: "store"; message: string } | 
/**  Lecture ou écriture de l'entrée de démarrage de Windows impossible. */
{ kind: "autostart"; message: string } | 
/**  Dossier des journaux impossible à créer ou à ouvrir. */
{ kind: "logs"; message: string };

export type AvailableDto = {
	version: string,
	/**  Texte brut (jamais du HTML) ; vide si la release n'en porte pas. */
	notes: string,
};

export type BlockedDto = "fingerprint_changed" | "incompatible_agent" | "incompatible_client";

export type CapabilitiesDto = {
	gpu: boolean,
	temps: boolean,
};

export type CpuInfoDto = {
	model: string,
	physicalCores: number | null,
	logicalCores: number,
	frequencyMhz: number | null,
};

export type DiskInfoDto = {
	name: string,
	mount: string,
	fs: string | null,
	totalBytes: number | null,
	removable: boolean,
};

export type DiskSampleDto = {
	name: string,
	mount: string,
	usedBytes: number | null,
	totalBytes: number | null,
};

/**
 *  Le certificat présenté n'est plus celui qui a été confirmé (BR-CONN-003). Les empreintes sont
 *  en 8 groupes de 4 pour l'affichage ; `presented_hex` est la forme complète à renvoyer pour
 *  l'accepter.
 */
export type FingerprintEvent = {
	serverId: string,
	expected: string,
	presented: string,
	presentedHex: string,
};

export type GpuInfoDto = {
	name: string,
	memoryTotalBytes: number | null,
};

export type GpuLevelsDto = {
	memory: LevelDto,
	temp: LevelDto,
};

export type GpuSampleDto = {
	name: string,
	loadPercent: number | null,
	memoryUsedBytes: number | null,
	memoryTotalBytes: number | null,
	/**  Absente quand la carte n'expose pas sa température (BR-DASH-007). */
	tempC: number | null,
};

export type InvalidField = "name" | "address" | "port" | "credentials" | "fingerprint" | "other";

export type LevelDto = "normal" | "attention" | "critical";

/**
 *  Niveau d'alerte de chaque mesure d'un échantillon (BR-DASH-003). Mêmes positions que les
 *  listes de l'échantillon (`disks[i]`, `gpus[i]`, `temps[i]`).
 */
export type LevelsDto = {
	cpu: LevelDto,
	mem: LevelDto,
	disks: LevelDto[],
	gpus: GpuLevelsDto[],
	temps: LevelDto[],
};

/**  Échec d'une commande de liaison, sans texte : l'interface choisit le message d'après `kind`. */
export type LinkFailure = 
/**  Adresse injoignable ou délai dépassé. */
{ kind: "unreachable" } | 
/**  Quelque chose répond, mais ce n'est pas un agent Hearth (BR-CONN-012). */
{ kind: "not_agent" } | 
/**  L'agent est trop ancien (BR-CONN-014). */
{ kind: "incompatible_agent" } | 
/**  Le client est trop ancien (BR-CONN-014). */
{ kind: "incompatible_client" } | 
/**  Identifiant ou mot de passe refusé, sans dire lequel (BR-CONN-013). */
{ kind: "invalid_credentials" } | { kind: "too_many_attempts"; retry_after_s: number } | { kind: "fingerprint_changed" } | { kind: "name_taken" } | { kind: "already_exists" } | 
/**  Champ invalide : `name`, `address`, `port` ou `credentials`. */
{ kind: "invalid_input"; field: InvalidField } | { kind: "verification_required" } | { kind: "unknown_server" } | { kind: "storage" } | { kind: "vault" } | 
/**  Le lien n'est pas « Connecté » : rien n'a été envoyé (BR-RESIL-008). */
{ kind: "not_connected" } | 
/**  Le suivi de l'action n'a pas pu être écrit sur le disque : l'action n'a PAS été lancée. */
{ kind: "tracking_unavailable" } | 
/**  Le disque est trop lent pour écrire le suivi à temps : l'action n'a PAS été lancée. */
{ kind: "tracking_slow" } | { kind: "internal" };

/**
 *  État du lien d'un serveur (`link://state`). `seq` croît strictement par serveur : l'interface
 *  écarte tout événement dont `seq` n'est pas supérieur au dernier connu.
 */
export type LinkStateDto = {
	serverId: string,
	seq: number,
	state: LinkStateName,
	since: number | null,
	lastContactAt: number | null,
	nextRetryAt: number | null,
	blocked: BlockedDto | null,
	reason: ReasonDto | null,
	failedAttempts: number,
};

export type LinkStateName = "connected" | "reconnecting" | "offline" | "session_expired" | "access_revoked";

export type LoginDto = {
	role: RoleDto,
	username: string,
};

/**  Identité de la machine (BR-DASH-001, 005, 006). */
export type MachineDto = {
	name: string,
	os: OsDto,
	cpu: CpuInfoDto,
	memoryTotalBytes: number | null,
	disks: DiskInfoDto[],
	gpus: GpuInfoDto[],
	capabilities: CapabilitiesDto,
};

export type MemoryDto = {
	usedBytes: number | null,
	totalBytes: number | null,
};

/**  Un échantillon en direct (`link://metrics`, chaque seconde). */
export type MetricsEvent = {
	serverId: string,
	sample: SampleDto,
	levels: LevelsDto,
};

export type NetDto = {
	upBytesPerS: number | null,
	downBytesPerS: number | null,
};

export type NoticeEvent = {
	/**  Numéro de l'avis retenu par la coquille (acquittement, dédoublonnage) ; 0 : non retenu. */
	id: number,
	kind: NoticeKind,
	serverId: string | null,
};

export type NoticeKind = 
/**  Les suivis d'actions d'un serveur étaient illisibles : vérifie l'état avant de relancer. */
"operations_lost" | 
/**  L'écoute a pris du retard : des changements ont pu être manqués (états relus). */
"lagged";

export type OperationEventDto = {
	opId: string,
	serverId: string,
	outcome: OutcomeDto,
};

export type OsDto = {
	name: string,
	version: string | null,
	kernel: string | null,
	arch: string,
};

export type OutcomeDto = "done" | "not_executed" | "unknown";

export type PasswordRuleDto = "required" | "min_length" | "digit" | "lowercase" | "uppercase" | "contains_username";

/**  Première prise de contact : l'empreinte à faire confirmer. */
export type ProbeDto = {
	/**  Forme complète (64 caractères hexadécimaux), à renvoyer à `add_server`. */
	fingerprint: string,
	/**  8 groupes de 4 caractères, pour l'affichage. */
	display: string,
	machineName: string,
	agentVersion: string,
	macAddresses: string[],
};

export type ReasonDto = "no_session" | "expired" | "stored_password_refused" | "user_disconnected" | "revoked";

export type RoleDto = "admin" | "readonly";

/**  Une seconde de la vie de la machine. */
export type SampleDto = {
	/**  Instant de la mesure (millisecondes depuis l'époque). */
	at: number | null,
	uptimeS: number | null,
	cpu: number | null,
	cores: (number | null)[],
	mem: MemoryDto,
	disks: DiskSampleDto[],
	net: NetDto | null,
	gpus: GpuSampleDto[],
	temps: TempDto[],
};

/**  Un serveur du carnet, sans secret. */
export type ServerDto = {
	id: string,
	name: string,
	/**  Adresse telle qu'on l'affiche : le port n'apparaît que s'il n'est pas celui par défaut. */
	address: string,
	host: string,
	port: number,
	/**  Numéro de la palette de 8 couleurs (1 à 8). */
	color: number,
	/**  Rôle à la dernière connexion ; lecture seule tant qu'on n'est jamais connecté. */
	role: RoleDto,
	username: string,
	remember: boolean,
};

export type ServersEvent = {
	servers: ServerDto[],
};

/**
 *  Réglages locaux, tels que l'interface les voit. Le fait que l'explication de
 *  fermeture ait été montrée reste interne à la coquille.
 */
export type Settings = {
	/**  Lancer Hearth au démarrage de Windows (désactivé par défaut, BR-CLIENT-006). */
	launchAtStartup: boolean,
};

/**
 *  Identité et historique (`link://snapshot`, et lecture `get_dashboard`). `levels` : ceux du
 *  dernier échantillon de `history`, s'il y en a un.
 */
export type SnapshotEvent = {
	serverId: string,
	machine: MachineDto,
	history: SampleDto[],
	levels: LevelsDto | null,
};

export type TempDto = {
	label: string,
	celsius: number | null,
};

/**
 *  Pourquoi la dernière mise à jour demandée n'a pas abouti. La version en cours reste utilisable
 *  dans tous les cas.
 */
export type UpdateFailure = 
/**  BR-UPDATE-009 : coupure ; relançable. */
"interrupted" | 
/**  BR-UPDATE-010 : signature ou contenu refusés. */
"corrupted" | 
/**  Autre échec. */
"failed";

export type UpdatePhase = "idle" | 
/**  Interrogation du flux de versions. */
"checking" | 
/**  Téléchargement de l'installateur (signature vérifiée à la fin, avant toute écriture). */
"downloading" | 
/**  Installateur lancé : le client va se fermer et se relancer. */
"installing";

export type UpdateStateDto = {
	/**  Croît à chaque publication : l'interface écarte tout état plus ancien que le dernier vu. */
	seq: number,
	currentVersion: string,
	phase: UpdatePhase,
	/**  Avancement du téléchargement, 0 à 100 ; absent hors téléchargement. */
	progress: number | null,
	available: AvailableDto | null,
	/**  Le bandeau « Nouvelle version disponible » doit être affiché (BR-UPDATE-003, 006). */
	bannerVisible: boolean,
	/**  Le bandeau reparaît à cette date (« Plus tard »). */
	postponedUntil: number | null,
	/**  Dernière vérification qui a obtenu une réponse (BR-UPDATE-007). */
	lastCheckedAt: number | null,
	/**  La dernière vérification a réussi et rien de plus récent n'existe : « Tu es à jour ». */
	upToDate: boolean,
	failure: UpdateFailure | null,
};

export type UsernameProblemDto = "empty" | "too_short" | "too_long" | "invalid_chars";

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

