// @ts-nocheck
/* eslint-disable */
// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	getSettings: () => typedError<Settings, AppError>(__TAURI_INVOKE("get_settings")),
	setLaunchAtStartup: (enabled: boolean) => typedError<Settings, AppError>(__TAURI_INVOKE("set_launch_at_startup", { enabled })),
	getAppVersion: () => __TAURI_INVOKE<string>("get_app_version"),
	openLogsFolder: () => typedError<null, AppError>(__TAURI_INVOKE("open_logs_folder")),
	/**
	 *  Erreur de l'interface (gestionnaire global Vue, rejet de promesse) à écrire au
	 *  journal du client. Jamais d'erreur en retour : l'interface ne doit pas
	 *  échouer en rapportant un échec. Message borné en taille, débit limité.
	 */
	logFrontendError: (source: string, message: string) => __TAURI_INVOKE<void>("log_frontend_error", { source, message }),
};

/* Types */
/**
 *  Erreur d'une commande. Sérialisée `{ kind, message }` côté TypeScript ;
 *  l'interface choisit son texte d'après `kind`.
 */
export type AppError = 
/**  Lecture ou écriture des réglages locaux impossible. */
{ kind: "store"; message: string } | 
/**  Lecture ou écriture de l'entrée de démarrage de Windows impossible. */
{ kind: "autostart"; message: string } | 
/**  Dossier des journaux impossible à créer ou à ouvrir. */
{ kind: "logs"; message: string };

/**
 *  Réglages locaux, tels que l'interface les voit. Le fait que l'explication de
 *  fermeture ait été montrée reste interne à la coquille.
 */
export type Settings = {
	/**  Lancer Hearth au démarrage de Windows (désactivé par défaut, BR-CLIENT-006). */
	launchAtStartup: boolean,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

